name: try_app

description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0
  lottie: ^3.1.2
  share_plus: ^10.0.0  # Updated to latest version
  shared_preferences: ^2.3.2
  carousel_slider: ^5.0.0  # Updated version
  line_icons: ^2.0.3
  image_picker: ^1.1.2  # Updated version
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  fluttertoast: ^8.2.12
  geolocator: ^14.0.0  # Updated version
  geocoding: ^3.0.0    # Updated version
  phonepe_payment_sdk: 2.0.3  # Updated version
  crypto: ^3.0.6
  sqflite: ^2.4.2      # Updated version
  firebase_messaging: ^15.2.6
  permission_handler: ^12.0.0  # Updated version
  chat_bubbles: ^1.7.0
  shimmer: ^3.0.0
  sms_autofill: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Updated version
  flutter_launcher_icons: ^0.14.3  # Updated version

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/sofacumbed.png
    - assets/page1.gif
    - assets/anim/anim_1.json
    - assets/anim/anim_2.json
    - assets/anim/anim_3.json
    - assets/anim/anim_4.json
    - assets/anim/anim_5.json
    - assets/anim/anim_6.json
    - assets/anim/anim_7.json
    - assets/anim/anim_8.json
    - assets/anim/anim_9.json
    - assets/anim/anim_10.json
    - assets/anim/anim_11.json
    - assets/icon/appliances.png
    - assets/icon/clothes.png
    - assets/icon/furniture.png
    - assets/icon/yacht_and_helicopters.png
    - assets/icon/home_.png
    - assets/icon/home_stay.png
    - assets/icon/hotels.png
    - assets/icon/property.png
    - assets/icon/tools.png
    - assets/icon/vehicle.png
    - assets/images/onboarding1.jpg


flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  android_adaptive_icon_foreground: assets/logo.png